branches:
  - main
repositoryUrl: https://github.com/dsmdavid/action-tableau-format-validator
plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"